name: Build using Bilt
'on':
  - push
jobs:
  generateBuildInformation:
    name: Generate 'Needs Build' information'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Install Bilt
        run: npm install -g @bilt/cli @bilt/github-actions-workflow
      - name: Generate build information
        id: generateBuildInformation
        run: bilt  --dry-run --json | github-actions-workflow echo-build-needs
    outputs:
      needs-build-_sample-bilt-monorepo__math-utils: >-
        ${{steps.generateBuildInformation.outputs.needs-build-_sample-bilt-monorepo__math-utils}}
      needs-build-_sample-bilt-monorepo__snake: >-
        ${{steps.generateBuildInformation.outputs.needs-build-_sample-bilt-monorepo__snake}}
      needs-build-_sample-bilt-monorepo__promise-utils: >-
        ${{steps.generateBuildInformation.outputs.needs-build-_sample-bilt-monorepo__promise-utils}}
      needs-build-_sample-bilt-monorepo__console-snake: >-
        ${{steps.generateBuildInformation.outputs.needs-build-_sample-bilt-monorepo__console-snake}}
  build-_sample-bilt-monorepo__math-utils:
    name: '@sample-bilt-monorepo/math-utils'
    runs-on: ubuntu-latest
    needs:
      - generateBuildInformation
    steps:
      - name: Debug outputs
        run: |
          echo <<EOF
            ${{toJSON(needs.generateBuildInformation.outputs)}}
          EOF
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Enable Git Push
        run: >
          git config --global user.email "bilt-ci@example.com"

          git config --global user.name "Bilt CI"

          git remote set-url origin https://x-access-token:${{
          secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: 'https://registry.npmjs.org'
      - name: Install Bilt
        run: npm install -g @bilt/cli
      - name: Run Verdaccio
        run: |
          cd dev
          npm install
          npm run develop-locally
      - name: Build
        run: bilt @sample-bilt-monorepo/math-utils -m 'CI Build'
    if: >-
      ${{needs.generateBuildInformation.outputs.needs-build-_sample-bilt-monorepo__math-utils
      == 'true'}}
  build-_sample-bilt-monorepo__snake:
    name: '@sample-bilt-monorepo/snake'
    runs-on: ubuntu-latest
    needs:
      - build-_sample-bilt-monorepo__math-utils
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Enable Git Push
        run: >
          git config --global user.email "bilt-ci@example.com"

          git config --global user.name "Bilt CI"

          git remote set-url origin https://x-access-token:${{
          secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: 'https://registry.npmjs.org'
      - name: Install Bilt
        run: npm install -g @bilt/cli
      - name: Run Verdaccio
        run: |
          cd dev
          npm install
          npm run develop-locally
      - name: Build
        run: bilt @sample-bilt-monorepo/snake -m 'CI Build'
    if: >-
      ${{needs.generateBuildInformation.outputs.needs-build-_sample-bilt-monorepo__snake
      == 'true'}}
  build-_sample-bilt-monorepo__promise-utils:
    name: '@sample-bilt-monorepo/promise-utils'
    runs-on: ubuntu-latest
    needs:
      - generateBuildInformation
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Enable Git Push
        run: >
          git config --global user.email "bilt-ci@example.com"

          git config --global user.name "Bilt CI"

          git remote set-url origin https://x-access-token:${{
          secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: 'https://registry.npmjs.org'
      - name: Install Bilt
        run: npm install -g @bilt/cli
      - name: Run Verdaccio
        run: |
          cd dev
          npm install
          npm run develop-locally
      - name: Build
        run: bilt @sample-bilt-monorepo/promise-utils -m 'CI Build'
    if: >-
      ${{needs.generateBuildInformation.outputs.needs-build-_sample-bilt-monorepo__promise-utils
      == 'true'}}
  build-_sample-bilt-monorepo__console-snake:
    name: '@sample-bilt-monorepo/console-snake'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Enable Git Push
        run: >
          git config --global user.email "bilt-ci@example.com"

          git config --global user.name "Bilt CI"

          git remote set-url origin https://x-access-token:${{
          secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: 'https://registry.npmjs.org'
      - name: Install Bilt
        run: npm install -g @bilt/cli
      - name: Run Verdaccio
        run: |
          cd dev
          npm install
          npm run develop-locally
      - name: Build
        run: bilt @sample-bilt-monorepo/console-snake -m 'CI Build'
    if: >-
      always() &&
      ${{needs.generateBuildInformation.outputs.needs-build-_sample-bilt-monorepo__console-snake == 'true' &&
      needs.generateBuildInformation.outputs.needs-build-_sample-bilt-monorepo__promise-utils.result != 'failure' &&
      needs.generateBuildInformation.outputs.needs-build-_sample-bilt-monorepo__snake.result != 'failure'}}

