name: Build sample-bilt-repo (parallel)
on: ['push']
jobs:
  generateBuildInformation:
    name: "Generate build information"
    runs-on: ubuntu-latest
    steps:
    - name: "Generate build information"
      id: "generateBuildInformation"
      run: |
        echo <<EOF
          ::set-output name=sample-bilt-monorepo__snake__needs::["generateBuildInformation", "@sample-bilt-monorepo/math-utils"]
        EOF
    outputs:
      sample-bilt-monorepo__snake__run: 'false'
  build-sample-bilt-monorepo__snake:
    if: ${{needs.generateBuildInformation.outputs.sample-bilt-monorepo__snake__run == 'true'}}
    name: "@sample-bilt-monorepo/snake"
    runs-on: ubuntu-latest
    needs:
      - generateBuildInformation
    steps:
    - name: "Build"
      run: |
        echo Result: ${{needs.generateBuildInformation.result}}
        echo Output: ${{needs.generateBuildInformation.outputs.sample-bilt-monorepo__snake__run}}
        echo not needy: ${{github.repository}}-${{github.ref}}