name: Build sample-bilt-repo (parallel)
on: ['push']
jobs:
  generate-build-information:
    name: "Generate build information"
    runs-on: ubuntu-latest
    steps:
    - name: "Generate build information"
      run: |
        echo ::set-output name=sample-bilt-monorepo__snake__needs::@sample-bilt-monorepo/math-utils
  build-sample-bilt-monorepo__snake:
    name: "@sample-bilt-monorepo/snake"
    runs-on: ubuntu-latest
    needs: "generate-build-information"
    steps:
    - name: "Build"
      run: |
        echo It works: ${{needs.generate-build-information.output.sample-bilt-monorepo__snake__needs}}!
