name: Build sample-bilt-repo (parallel)
on: ['push']
jobs:
  generateBuildInformation:
    name: "Generate build information"
    runs-on: ubuntu-latest
    steps:
    - name: "Generate build information"
      id: "generateBuildInformation"
      run: |
        echo <<EOF
          ::set-output name=needs-build-_sample-bilt-monorepo__math-utils::false
          ::set-output name=needs-build-_sample-bilt-monorepo__promise-utils::true
          ::set-output name=needs-build-_sample-bilt-monorepo__snake::true
          ::set-output name=needs-build-_sample-bilt-monorepo__console-snake::true
        EOF
    outputs:
      needs-build-_sample-bilt-monorepo__math-utils: ${{steps.generateBuildInformation.outputs.needs-build-_sample-bilt-monorepo__math-utils}}
      needs-build-_sample-bilt-monorepo__promise-utils: ${{steps.generateBuildInformation.outputs.needs-build-_sample-bilt-monorepo__promise-utils}}
      needs-build-_sample-bilt-monorepo__snake: ${{steps.generateBuildInformation.outputs.needs-build-_sample-bilt-monorepo__snake}}
      needs-build-_sample-bilt-monorepo__console-snake: ${{steps.generateBuildInformation.outputs.needs-build-_sample-bilt-monorepo__console-snake}}
  build-_sample-bilt-monorepo__math-utils:
    name: "@sample-bilt-monorepo/math-utils"
    if: ${{needs.generateBuildInformation.outputs.needs-build-_sample-bilt-monorepo__math-utils == 'true'}}
    runs-on: ubuntu-latest
    needs:
      - generateBuildInformation
    steps:
    - name: "Build"
      run: |
        bilt @sample-bilt-monorepo/math-utils -m 'CI Build'
  build-_sample-bilt-monorepo__promise-utils:
    name: "@sample-bilt-monorepo/promise-utils"
    if: ${{needs.generateBuildInformation.outputs.needs-build-_sample-bilt-monorepo__promise-utils == 'true'}}
    runs-on: ubuntu-latest
    needs:
      - generateBuildInformation
    steps:
    - name: "Build"
      run: |
        bilt @sample-bilt-monorepo/promise-utils -m 'CI Build'
  build-_sample-bilt-monorepo__snake:
    name: "@sample-bilt-monorepo/snake"
    if: ${{needs.generateBuildInformation.outputs.needs-build-_sample-bilt-monorepo__snake == 'true'}}
    runs-on: ubuntu-latest
    needs:
      - generateBuildInformation
      - build-_sample-bilt-monorepo__math-utils
    steps:
    - name: "Build"
      run: |
        bilt @sample-bilt-monorepo/snake -m 'CI Build'
  build-_sample-bilt-monorepo__console-snake:
    name: "@sample-bilt-monorepo/console-snake"
    if: ${{needs.generateBuildInformation.outputs.needs-build-_sample-bilt-monorepo__console-snake == 'true'}}
    runs-on: ubuntu-latest
    needs:
      - generateBuildInformation
      - build-_sample-bilt-monorepo__promise-utils
      - build-_sample-bilt-monorepo__snake
    steps:
    - name: "Build"
      run: |
        bilt @sample-bilt-monorepo/console-snake -m 'CI Build'
