name: Build sample-bilt-repo (parallel)
on: ['push']
jobs:
  generateBuildInformation:
    name: "Generate build information"
    runs-on: ubuntu-latest
    steps:
    - name: "Generate build information"
      id: "generateBuildInformation"
      run: |
        echo ::set-output name=sample-bilt-monorepo__snake__needs::@sample-bilt-monorepo/math-utils
        echo ::warning file=lalala,line=111,col=111::oops
        echo '::set-output name=x::y'
    outputs:
      x: ${{steps.generateBuildInformation.outputs.x}}
  build-sample-bilt-monorepo__snake:
    name: "@sample-bilt-monorepo/snake"
    runs-on: ubuntu-latest
    needs: "generateBuildInformation"
    steps:
    - name: "Build"
      run: |
        echo Result: ${{needs.generateBuildInformation.result}}
        echo Output: <<EOF
        ${{toJSON(needs.generateBuildInformation)}}
        EOF
        echo Output: ${{needs.generateBuildInformation.x}}}
        echo not needy: ${{github.repository}}-${{github.ref}}
