name: Build sample-bilt-repo
on: ['push', 'pull_request']
jobs:
  build:
    name: "Build monorepo using Bilt"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Enable Git Push
        run: |
          git config --global user.email "bilt-ci@tayar.org"
          git config --global user.name "Bilt CI"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: 'https://registry.npmjs.org'
      - name: Install Bilt
        run: |
          npm install -g npm@latest
          npm install -g @bilt/cli
      - name: Run Verdaccio
        run: |
          cd dev
          npm install
          npm run develop-locally
      - name: Bilt
        run: |
          bilt -m "build from CI" --no-before
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
