name: Build sample-bilt-repo (parallel)
on: ['push']
jobs:
  generateBuildInformation:
    name: "Generate build information"
    runs-on: ubuntu-latest
    steps:
    - name: "Generate build information"
      id: "generateBuildInformationStep"
      run: |
        # echo ::set-output name=sample-bilt-monorepo__snake__needs::@sample-bilt-monorepo/math-utils
        echo ::warning file=lalala,line=111,col=111::oops
        echo '::set-output name=x::y'
    - name: "Use build information"
      run: |
        echo << EOF
        ${{toJSON(steps)}}
        EOF
  build-sample-bilt-monorepo__snake:
    name: "@sample-bilt-monorepo/snake"
    runs-on: ubuntu-latest
    needs: "generateBuildInformation"
    steps:
    - name: "Build"
      run: |
        echo Result: ${{needs.generateBuildInformation.result}}
        echo Output: ${{toJSON(needs)}}
        echo not needy: ${{github.repository}}-${{github.ref}}
